# Generated by Django 4.2.7 on 2023-12-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ref',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
