# Generated by Django 4.2.7 on 2023-12-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_ref_transaction_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='full_name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='first_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
