# Generated by Django 5.0 on 2023-12-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_full_name_transaction_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='matriculation_number',
            field=models.CharField(max_length=13),
        ),
    ]
