# Generated by Django 4.2.7 on 2023-11-13 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_alter_levy_options_remove_department_levy_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='levy',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
