# Generated by Django 4.2.7 on 2023-12-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile_app', '0002_user_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
